### ISSUE TITLE
Instructor Feedback

### ISSUE THREAD

**Issue by droxey** [woodward4422/contractor_project_BEW1.1#1]
Great work, @woodward4422!

In order to pass this project, a few changes need to be made by EOD today:

- Add 100% test coverage for all routes.
- Change bootstrap 3.3.7 link in `main.handlebars` to use Bootstrap 4 as in the requirements.

Thanks!
-d

**Comment by woodward4422** [comment]
Added tests and changed over the Bootstrap link to 4.0.0. Thanks!

**Comment by droxey** [comment]
Thanks Noah! This is now passing! 👍
